name: Install winget
description: Installs the latest version of winget
author: Dominion/Cyberboss
branding:
  icon: arrow-down-circle
  color: blue
inputs:
  GITHUB_TOKEN:
    description: 'No scopes GitHub token for querying the API and downloading from winget-cli releases'
    required: false
    default: 'NONE'
outputs:
  winget-version:
    description: "The version of winget installed"
    value: ${{ steps.winget-version.outputs.winget-version }}
runs:
# Hacked together https://github.com/microsoft/winget-cli/issues/1861#issuecomment-1352784247
# https://github.com/microsoft/winget-cli/issues/700#issuecomment-874084714
  using: composite
  steps:
    - name: Install winget
      shell: powershell
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Install-PackageProvider -Name NuGet -Force | Out-Null
        Install-Module -Name Microsoft.WinGet.Client -Force -Repository PSGallery | Out-Null
        Repair-WinGetPackageManager

    - name: Wait to allow Installation to Finalize
      shell: powershell
      run: |
        foreach ($i in 1..60) {
          Start-Sleep -Seconds 1
          Write-Host "Waiting for winget to install... ${i}"
          if (Get-Command winget -ErrorAction SilentlyContinue) {
            break
          }
        }

    - name: Output winget Version
      id: winget-version
      shell: powershell
      run: |
        $version=winget --version
        Write-Host "$version"
        Write-Output "winget-version=$version" >> $Env:GITHUB_OUTPUT

